# Generated by Django 3.0.6 on 2020-05-24 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('body', models.TextField(verbose_name='cuerpo')),
                ('created', models.DateField(auto_now_add=True, verbose_name='creado')),
                ('publish', models.DateField(auto_now=True, verbose_name='publicado')),
                ('updated', models.DateField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=100, unique_for_date='publish')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
